import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import localFont from 'next/font/local';

import "./globals.css";
import { cn } from "@/lib/utils";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const diaplay_font = localFont({
  src: './fonts/ORTUS.otf',
  variable: '--font-display',
  display: 'swap',
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        outfit.className,
        diaplay_font.variable,
        "antialiased "
      )}>{children}</body>
    </html>
  );
}
